# Generated by Django 4.2 on 2026-01-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mauribus_app', '0002_alter_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='mauribus_app.driver'),
        ),
        migrations.AddField(
            model_name='bus',
            name='lat',
            field=models.FloatField(default=14.7),
        ),
        migrations.AddField(
            model_name='bus',
            name='lng',
            field=models.FloatField(default=-17.44),
        ),
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('service', 'En Service'), ('panne', 'En Panne'), ('maintenance', 'Maintenance'), ('garage', 'Au Garage')], default='service', max_length=20),
        ),
    ]
