# Generated by Django 4.2 on 2026-01-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauribus_app', '0004_trip_completed_at_trip_started_at_trip_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='end_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='end_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='start_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
