# Generated by Django 4.2 on 2026-01-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauribus_app', '0005_line_end_lat_line_end_lng_line_start_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
    ]
